INSERT INTO TEST.TEST (ID, NAME, AGE, ISADMIN) VALUES ('1', 'First user', '12', '0');
INSERT INTO TEST.TEST (ID, NAME, AGE, ISADMIN) VALUES ('2', 'Second user', '24', '1');
INSERT INTO TEST.TEST (ID, NAME, AGE, ISADMIN) VALUES ('3', 'Third user', '13', '0');
INSERT INTO TEST.TEST (ID, NAME, AGE, ISADMIN) VALUES ('4', 'Fourth user', '99', '0');
